import { SEO } from '@components/common/seo';

export default function Home(): JSX.Element {
  return (
    <main>
      <SEO
        title='Next.js Template'
        description='Generated by create next app.'
      />
    </main>
  );
}
